### ISSUE TITLE
Student Project Template

### ISSUE THREAD

**Issue by dotinceptionsai** [dotinceptionsai/team-aajk#1]
## References

We can use the provided capstone ideation and project templates as reference material.

[Capstone Ideation Write-Up](https://github.com/dotinceptionsai/team-aajk/blob/main/docs/capstone-ideation-write-up.pdf)
[Project Scoping Form](https://github.com/dotinceptionsai/team-aajk/blob/main/docs/project-scoping-form.pdf)

**Comment by thirionjl** [comment]
As we will provide an app we can close this issue about not branching out of the notebook... It will particularly be interesting to properly manage the Devops MLops part. 

Build, model versioning, deploy... And maybe continuous performance monitoring and retraining...
